cc_test(
    name = "test_helpers",
    srcs = ["test_helpers.cpp"],
    deps = [
        "//src/helpers:helpers",
        "@com_google_googletest//:gtest_main"
    ]
)

cc_test(
    name = "test_unnamed_protocol_header",
    srcs = ["test_unnamed_protocol_header.cpp"],
    deps = [
        "//src/unnamed_protocol:unnamed_protocol",
        "@com_google_googletest//:gtest_main"
    ]
)

cc_test(
    name = "test_unnamed_protocol_socket_handler",
    srcs = ["test_unnamed_protocol_connection.cpp"],
    deps = [
        "//src/unnamed_protocol:unnamed_protocol",
        "@com_google_googletest//:gtest_main"
    ]
)
