cc_test(
    name = "test_helpers",
    srcs = ["test_helpers.cpp"],
    deps = [
        "//src:helpers",
        "@com_google_googletest//:gtest_main"
    ]
)

cc_test(
    name = "test_tcp_header",
    srcs = ["test_tcp_header.cpp"],
    deps = [
        "//src:helpers",
        "@com_google_googletest//:gtest_main"
    ]
)
