cc_library(
    name = "helpers",
    hdrs = glob(["*.hpp"]),
    srcs = glob(["*.cpp"]),
    deps = [
        "//:ncurses",
        "//src/helpers/ncurses_wrappers",
    ],
    visibility = ["//visibility:public"],
)
