cc_library(
    name = "unnamed_protocol",
    hdrs = glob(["*.hpp"]),
    srcs = glob(["*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/common:common",
        "//src/helpers:helpers"
    ],
)
