cc_library(
    name = "view_states",
    hdrs = glob(["*.hpp"]),
    srcs = glob(["*.cpp"]),
    deps = [
        "//src/helpers:helpers",
        "//src/logger:logger",
        "//src/helpers/ncurses_wrappers:ncurses_wrappers",
        "//src/unnamed_protocol:unnamed_protocol",
    ],
    visibility = ["//visibility:public"],
)
